id: A8BAA9F64
title: Aspiration for the Stages of the Path
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:08:35.260219
  last_modified_at: 2022-03-01 04:08:35.260226
