id: A8BAA9F64
title: The Foundation of All Qualities
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:08:35.263512
  last_modified_at: 2022-03-01 04:08:35.263516
